<a href="https://colab.research.google.com/github/RezaRejo/Final-Project-Data-Science/blob/main/Data_Cleaning_Gym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Preparation

In [ ]:
import pandas as pd
import numpy as np

##Access to Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Read Data

In [ ]:
file_path = '/content/drive/MyDrive/Dibimbing DS33B+/FINAL PROJECT DS DA/PROJECT/gym_membership.csv'
df = pd.read_csv(file_path)
df.head()

,id,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,...,personal_training,name_personal_trainer,uses_sauna,last_visit_date,Recency,abonoment_value,personal_training_val,drink_abo_val,sauna_val,Monetary
0,1,Female,1997-04-18,27,Premium,4,"Mon, Sat, Tue, Wed",True,"Kickboxen, BodyPump, Zumba",19:31:00,...,False,NaN,True,2025-05-02,51,2,0,0,1,250
1,2,Female,1977-09-18,47,Standard,3,"Mon, Sat, Wed",False,NaN,19:31:00,...,True,Chantal,False,2025-06-08,14,1,1,0,0,180
2,3,Male,1983-03-30,41,Premium,1,Sat,True,XCore,08:29:00,...,True,Mike,False,2025-04-12,71,2,1,1,0,280
3,4,Male,1980-04-12,44,Premium,3,"Sat, Tue, Wed",False,NaN,09:54:00,...,True,Mike,True,2025-04-23,60,2,1,1,1,310
4,5,Male,1980-09-10,44,Standard,2,"Thu, Wed",True,"Running, Yoga, Zumba",08:29:00,...,True,Mike,False,2025-06-02,20,1,1,0,0,170

#Data Cleaning

In [ ]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   gender                 1000 non-null   object
 2   birthday               1000 non-null   object
 3   Age                    1000 non-null   int64
 4   abonoment_type         1000 non-null   object
 5   visit_per_week         1000 non-null   int64
 6   days_per_week          1000 non-null   object
 7   attend_group_lesson    1000 non-null   bool
 8   fav_group_lesson       503 non-null    object
 9   avg_time_check_in      1000 non-null   object
 10  avg_time_check_out     1000 non-null   object
 11  avg_time_in_gym        1000 non-null   int64
 12  drink_abo              1000 non-null   bool
 13  fav_drink              496 non-null    object
 14  personal_training      1000 non-null   bool
 15  name_personal_trainer  518 non-null    object
 16  uses_sauna             1000 non-null   bool
 17  last_visit_date        1000 non-null   object
 18  Recency                1000 non-null   int64
 19  abonoment_value        1000 non-null   int64
 20  personal_training_val  1000 non-null   int64
 21  drink_abo_val          1000 non-null   int64
 22  sauna_val              1000 non-null   int64
 23  Monetary               1000 non-null   int64
dtypes: bool(4), int64(10), object(10)
memory usage: 160.3+ KB

,id,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,...,personal_training,name_personal_trainer,uses_sauna,last_visit_date,Recency,abonoment_value,personal_training_val,drink_abo_val,sauna_val,Monetary
count,1000.000000,1000,1000,1000.000000,1000,1000.000000,1000,1000,503,1000,...,1000,518,1000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
unique,NaN,2,974,NaN,2,NaN,115,2,253,556,...,2,4,2,90,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Female,1976-09-28,NaN,Standard,NaN,Sun,True,BodyPump,17:57:00,...,True,Chantal,False,2025-04-22,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,503,2,NaN,507,NaN,37,503,20,6,...,518,153,507,23,NaN,NaN,NaN,NaN,NaN,NaN
mean,500.500000,NaN,NaN,30.604000,NaN,2.682000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,43.271000,1.493000,0.518000,0.496000,0.493000,216.870000
std,288.819436,NaN,NaN,10.817958,NaN,1.241941,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,26.364914,0.500201,0.499926,0.500234,0.500201,59.785261
min,1.000000,NaN,NaN,12.000000,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,110.000000
25%,250.750000,NaN,NaN,21.000000,NaN,2.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.000000,1.000000,0.000000,0.000000,0.000000,160.000000
50%,500.500000,NaN,NaN,30.000000,NaN,3.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,44.000000,1.000000,1.000000,0.000000,0.000000,220.000000
75%,750.250000,NaN,NaN,40.000000,NaN,3.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,64.000000,2.000000,1.000000,1.000000,1.000000,270.000000
max,1000.000000,NaN,NaN,49.000000,NaN,5.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,89.000000,2.000000,1.000000,1.000000,1.000000,330.000000

##Cek Duplicat

In [ ]:
#cek ada duplicat atau tidak
df.duplicated().sum()

np.int64(0)

In [ ]:
#Menstandarkan nama kolom
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

##Cek null

In [ ]:
print(df.isnull().sum())

id                         0
gender                     0
birthday                   0
age                        0
abonoment_type             0
visit_per_week             0
days_per_week              0
attend_group_lesson        0
fav_group_lesson         497
avg_time_check_in          0
avg_time_check_out         0
avg_time_in_gym            0
drink_abo                  0
fav_drink                504
personal_training          0
name_personal_trainer    482
uses_sauna                 0
last_visit_date            0
recency                    0
abonoment_value            0
personal_training_val      0
drink_abo_val              0
sauna_val                  0
monetary                   0
dtype: int64

Kita drop nilai null dan tidak perlu digunakan

In [ ]:
df_clean = df.drop(columns=['fav_group_lesson', 'fav_drink', 'name_personal_trainer'])
df_clean.head()

,id,gender,birthday,age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,avg_time_check_in,avg_time_check_out,...,drink_abo,personal_training,uses_sauna,last_visit_date,recency,abonoment_value,personal_training_val,drink_abo_val,sauna_val,monetary
0,1,Female,1997-04-18,27,Premium,4,"Mon, Sat, Tue, Wed",True,19:31:00,21:27:00,...,False,False,True,2025-05-02,51,2,0,0,1,250
1,2,Female,1977-09-18,47,Standard,3,"Mon, Sat, Wed",False,19:31:00,20:19:00,...,False,True,False,2025-06-08,14,1,1,0,0,180
2,3,Male,1983-03-30,41,Premium,1,Sat,True,08:29:00,10:32:00,...,True,True,False,2025-04-12,71,2,1,1,0,280
3,4,Male,1980-04-12,44,Premium,3,"Sat, Tue, Wed",False,09:54:00,11:33:00,...,True,True,True,2025-04-23,60,2,1,1,1,310
4,5,Male,1980-09-10,44,Standard,2,"Thu, Wed",True,08:29:00,09:19:00,...,False,True,False,2025-06-02,20,1,1,0,0,170

##Format tanggal

In [ ]:
if 'birthday' in df.columns:
    df['birthday'] = pd.to_datetime(df['birthday'], errors='coerce')
if 'last_visit_date' in df.columns:
    df['last_visit_date'] = pd.to_datetime(df['last_visit_date'], errors='coerce')

Memastikan konsistensi kategori

In [ ]:
if 'gender' in df.columns:
    df['gender'] = df['gender'].str.strip().str.upper()

##Konversi tipe data numerik

In [ ]:
for col in df.columns:
    if df[col].dtype == 'object':
        try:
            df[col] = df[col].str.replace(',', '').astype(float)
        except:
            continue

##Groping gender dan abonoment type

In [ ]:
df_grouped = df.groupby(['gender', 'abonoment_type']).size().reset_index(name='count')
df_grouped

   gender abonoment_type  count
0  FEMALE        Premium    242
1  FEMALE       Standard    261
2    MALE        Premium    251
3    MALE       Standard    246

In [ ]:
df_clean.head()

,id,gender,birthday,age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,avg_time_check_in,avg_time_check_out,...,drink_abo,personal_training,uses_sauna,last_visit_date,recency,abonoment_value,personal_training_val,drink_abo_val,sauna_val,monetary
0,1,Female,1997-04-18,27,Premium,4,"Mon, Sat, Tue, Wed",True,19:31:00,21:27:00,...,False,False,True,2025-05-02,51,2,0,0,1,250
1,2,Female,1977-09-18,47,Standard,3,"Mon, Sat, Wed",False,19:31:00,20:19:00,...,False,True,False,2025-06-08,14,1,1,0,0,180
2,3,Male,1983-03-30,41,Premium,1,Sat,True,08:29:00,10:32:00,...,True,True,False,2025-04-12,71,2,1,1,0,280
3,4,Male,1980-04-12,44,Premium,3,"Sat, Tue, Wed",False,09:54:00,11:33:00,...,True,True,True,2025-04-23,60,2,1,1,1,310
4,5,Male,1980-09-10,44,Standard,2,"Thu, Wed",True,08:29:00,09:19:00,...,False,True,False,2025-06-02,20,1,1,0,0,170

#Simpan hasil clean ke file baru

In [ ]:
df_clean.to_csv("gym_membership_cleaned.csv", index=False)
print("✅ Data cleaning selesai. File disimpan sebagai 'gym_membership_cleaned.csv'")

✅ Data cleaning selesai. File disimpan sebagai 'gym_membership_cleaned.csv'